version: 0.2
import:
  - https://cdn.jsdelivr.net/npm/@cspell/dict-people-names/cspell-ext.json
ignorePaths:
  - elections/**/*
  - tools/github/*
  - scripts/**/*.py
  - scripts/**/*.sh
  - CODEOWNERS
patterns:
  - name: Slack Channel ID
    pattern: "id: [A-Z0-9]{11}"
  - name: Google Docs ID
    pattern: "value: [a-zA-Z0-9-_]+"
  - name: GitHub Handle
    pattern: "@[a-zA-Z0-9-_]+\\b"
  - name: GitHub Handle in YML
    pattern: "github: [a-zA-Z0-9-_]+"
  - name: HTML href
    pattern: "href=([\"'])[^~`]*?\\1"    
  - name: HTML comment
    pattern: "<!--.*-->"
  - name: CodeName
    pattern: "/([~`])[^~`]*?\\1/gmx"
dictionaries:
  - java
  - makefile
  - markdown
  - node
  - python
  - people-names
  - companies
  - php
  - javascript
  - softwareTerms
  - software-tools
ignoreWords:
  - devex
  - hostmetrics
  - hostmetricsreceiver
  - Instrgen
  - k8sclusterreceiver
  - rolldice
  - zhcn
  - ptbr
enabledLanguageIds:
  - makefile
  - yaml
languageSettings:
  - languageId: markdown
    ignoreRegExpList:
      - GitHub Handle
      - HTML href
      - HTML comment
      - CodeName
  - languageId: makefile, yaml
    includeRegExpList:
      - "/[^']#.*/g"
    ignoreRegExpList:
      - Slack Channel ID
      - Google Docs ID
      - GitHub Handle in YML
words:
  - cicd
  - genai
  - KubeCon
  - semconv
  - OpAMP
  - OTAP
  - OTel
  - otelbot
  - OTEP
  - OTTL

  - DASD
  - REXX
  - Sysplex

  - ADOT
  - Arize
  - Codecentric
  - Credly
  - Heptio
  - Jemmic
  - Langfuse
  - Langtrace
  - Liatrio
  - Logz
  - ObservIQ
  - Olly
  - Outreachy
  - QuesmaOrg
  - Traceloop
  - VTEX

  - develocity
  - DocuSign
  - dosu
  - easycla
  - Keptn
  - OpenLLMetry
  - Tekton
  - gitdm

  - subproject
  - subprojects
  - maintainership
  - roadmaps
  - signup
  - supermajority
  - tiebreaking
  - uninstrumented
  - passcodes
  - timeslot
